# Generated by Django 5.0.1 on 2024-01-12 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_entry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name_plural": "Entries"},
        ),
    ]
