# Generated by Django 5.0.1 on 2024-01-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_matching_entry_knows_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="email",
            field=models.EmailField(default="default@localhost", max_length=254),
            preserve_default=False,
        ),
    ]
