# Generated by Django 5.0.1 on 2024-01-15 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_entry_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="knows_about",
            new_name="has_received",
        ),
    ]
