# Generated by Django 5.0.1 on 2024-01-15 02:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_rename_knows_about_entry_has_received"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matching",
            old_name="informed",
            new_name="person_who_received",
        ),
    ]
