# Generated by Django 5.0.1 on 2024-01-15 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_rename_informed_matching_person_who_received"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matching",
            old_name="content",
            new_name="person_who_was_received",
        ),
    ]
