# Generated by Django 5.0.1 on 2024-01-15 04:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_rename_content_matching_person_who_was_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
