# Generated by Django 5.0.1 on 2024-01-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_entry_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matchlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
