# Generated by Django 5.0.1 on 2024-01-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_matchlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
