name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff
    - name: Run Tests
      run: |
        python manage.py collectstatic --noinput
        python manage.py test
      env:
        DEBUG: '1'
        SECRET_KEY: 'xxx'
    - name: Lint
      run: ruff check . && ruff check --select I .
